### ISSUE TITLE
Some URIs need to be updated. 

### ISSUE THREAD

**Issue by kern3020** [BikLab/lab-onboarding#1]
Hello,

Just thought I would mention a small nit which is neither urgent nor
important but will lead to a better experience for the next
person. Some of the URIs in your md files need to be updated. For example

```
./grad-students.md:* Creer et al. (2016) [The ecologists field guide to sequenced-based identification of biodiversity](https://biklab.github.io/assets/pdfs/Creer-etal-2016-MEE-EcolFieldGuide.pdf) _Methods in Ecology and Evolution_
./grad-students.md:* Bik et al. (2012) [Sequencing our way to understanding global eukaryotic biodiversity](https://biklab.github.io/assets/pdfs/Bik-2012-TREE-EukReview.pdf), _Trends in Ecology and Evolution_
```

I have found them view you're website
(https://www.biklab.org/publications). Normally I would just submit a
PR with right URIs.  Seems there are two choices your github
repository or doi.org.  As a non-academic, I don't know which is
preferred.

-jk

**Comment by hollybik** [comment]
Thanks for noticing this! I've gone ahead and updated the markdown file links to the correct PDFs and new lab website.
